### ISSUE TITLE
Header Image Upload Not Working

### ISSUE THREAD

**Issue by rganderson** [TJTorola/Samwise#5]
Unable to upload images to change header image

![image](https://cloud.githubusercontent.com/assets/1831329/17110744/57817ace-5253-11e6-8a20-53c05d19ca08.png)

**Comment by TJTorola** [comment]
Could you post the image you are trying to upload for me?

**Comment by rganderson** [comment]
![panorover head](https://cloud.githubusercontent.com/assets/1831329/17112151/a88f06f6-5259-11e6-9815-362ef9c379e0.jpg)

**Comment by TJTorola** [comment]
Ah ok I found the error. If I have time I'll fix/test and push it tonight.
